### PR TITLE
translation en -> kr

### PR DESCRIPTION
**Pull request by ProgC**
billboards tutorial

### CODE REVIEW

**Comment by ProgC** [comment]
This is first time! please let me know if I did pull request wrongly.

**Comment by Calvin1602** [comment]
It's perfect ! Thanks for the contribution. I was in Korea (!) on jan 10 and completely forgot to merge. Sorry for the long response time !

**Comment by ProgC** [comment]
Don't worry! Good news is there was no problem :)

**Comment by opengl-tutorial** [comment]
Nice ! The translation should be visible on the website.

Thank you very much !

**Pull request merged**
