### PR TITLE
Start Hungarian translation

### PR DESCRIPTION
**Pull request by mandyedi**

### CODE REVIEW

**Comment by Calvin1602** [comment]
Awesome. Thank you very much !!!

**Comment by mandyedi** [comment]
Thanks for merging!

It seems that I messed up the titles in header, because they are always in Hungarian. :/
I'm going to fix it asap (today evening).

**Comment by Whiteseeker** [comment]
I'm fixing it, the website has a lot of views every hours ...

**Comment by Whiteseeker** [comment]
Fixed in
https://github.com/opengl-tutorials/ogl/commit/fc24bd43934602f4d3361ee3a58a2036072ea09d

**Comment by Whiteseeker** [comment]
Thx a lot for the translation ! It looks really nice !
You could make it even more perfect by translating the title like here:
---
layout: tutorial
status: publish
published: true
**title: 'Tutorial 1 : Opening a window'**
date: '2011-04-07 17:54:16 +0200'
date_gmt: '2011-04-07 17:54:16 +0200'
categories: [tuto]
order: 10
tags: []
language: hu
---

**Comment by mandyedi** [comment]
Thanks for the fix and the tip too!

**Pull request merged**
